### PR TITLE
Added support to new runtime permissions model of Android M

### PR DESCRIPTION
**Pull request by josemedaglia**

### CODE REVIEW

**Comment by jaypatel512** [comment]
What are your thoughts on somehow re-using the runtime permissions code in [card.io-Android-Source](https://github.com/card-io/card.io-Android-source/blob/master/card.io/src/main/java/io/card/payment/CardIOActivity.java#L374) native implementation ?

**Comment by benjefferies** [comment]
I am getting issues on android 6 where it doesn't open the camera. Is this the behaviour you were seeing?

**Comment by josemedaglia** [comment]
Hi @jaypatel512, it's interesting Card.io already supported in some way the new Android permission model, I've just tested and it is working when you actually call the scan method. The problem I was seeing is that they didn't implement request for permissions for canReadCardWithCamera method (used by canScan method of the Cordova plugin).

It it's implemented in Card.io then there is no need to add it to the plugin, I'm going to report the issue to the other repo.

**Comment by josemedaglia** [comment]
Yeah I've just noticed!
I'm going to close this pull request then and wait for the issue to be resolved in Card.io.

Thanks

**Pull request closed without merging**
